# baseURL = "http://example.com/"
languageCode = "en-us"
title = "東京ライフハッカー"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
publishDir = "docs" # ビルド時の出力ディレクトリ

[params]
author = "Calin Tataru"
description = "Personal blog theme powered by Hugo"
githubUsername = "#"
accent = "#3eccbf"
showBorder = true
backgroundColor = "white"
font = "Raleway" # should match the name on Google Fonts!
highlight = true
highlightStyle = "default"
highlightLanguages = ["javascript", "toml", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "ホーム"
    weight = 1

[[menu.main]]
    url = "/programing/"
    name = "プログラミング"
    weight = 2

[[menu.main]]
    url = "/categories/"
    name = "カテゴリ"
    weight = 3

[[menu.main]]
    url = "/tags/"
    name = "タグ"
    weight = 4

# [[menu.main]]
#     url = "/series/"
#     name = "シリーズ"
#     weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

# [[menu.icon]]
#     url = "mailto:me@example.com"
#     name = "fas fa-envelope"
#     weight = 1

# [[menu.icon]]
#     url = "https://github.com/username/"
#     name = "fab fa-github"
#     weight = 2

# [[menu.icon]]
#     url = "https://twitter.com/username/"
#     name = "fab fa-twitter"
#     weight = 3

# [[menu.icon]]
#     url = "https://www.linkedin.com/in/username/"
#     name = "fab fa-linkedin"
#     weight = 4

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "fab fa-stack-overflow"
#     weight = 5
