languageCode = "ja-jp"
title = "東京のほほんライフハック"
theme = "original"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
publishDir = "docs" # ビルド時の出力ディレクトリ

[params]
author = "Calin Tataru"
description = "世田谷ぐらしのITエンジニアのメモ"
githubUsername = "#"

# デザインを指定
accent = "#3eccbf" # アクセントの色
showBorder = true # 上下にボーダーカラーを表示するかどうか

highlight = true
highlightStyle = "default"
highlightLanguages = ["javascript", "toml"]

fontCss = "Noto Serif JP"
fontLink = "https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@200;700&display=swap" # should match the name on Google Fonts!

# profileImage = "images/profile.jpg"

icon = "images/icon.png"

topImage = "images/tokyo.jpg"

copyright = "&copy; All rights reserved. Powered by トール."

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[[menu.main]]
    url = "/programing/"
    name = "プログラミング"
    weight = 2

[[menu.main]]
    url = "/categories/"
    name = "カテゴリ"
    weight = 3

[[menu.main]]
    url = "/tags/"
    name = "タグ"
    weight = 4

[[menu.main]]
    url = "/series/"
    name = "シリーズ"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

# [[menu.icon]]
#     url = "mailto:me@example.com"
#     name = "fas fa-envelope"
#     weight = 1

# [[menu.icon]]
#     url = "https://github.com/username/"
#     name = "fab fa-github"
#     weight = 2

# [[menu.icon]]
#     url = "https://twitter.com/username/"
#     name = "fab fa-twitter"
#     weight = 3

# [[menu.icon]]
#     url = "https://www.linkedin.com/in/username/"
#     name = "fab fa-linkedin"
#     weight = 4

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "fab fa-stack-overflow"
#     weight = 5
