title = "ちょいハック"
theme = "darkwhite"
languageCode = "ja-jp"
googleAnalytics = "G-MS2GT03MFC"
paginate = 5 #frontpage pagination
hasCJKLanguage = true
publishDir = "docs" # ビルド時の出力ディレクトリ

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
favicon = "img/favicon.ico"
copyright = "&copy; All rights reserved. Powered by トール."
header_image = "img/tokyo3.jpg"
SEOTitle = "プログラミングを中心に、現役web系エンジニアが興味を持ったことを徒然と書いていきます"
description = "プログラミングを中心に、現役web系エンジニアが興味を持ったことを徒然と書いていきます"
keyword = "programming, software, blog、プログラミング、エンジニア"
# slogan = "programming and rock climbing"
# image_404 = "img/404-bg.jpg"
title_404 = "404 Not Found"
omit_categories = false

# -- algolia site search --
# algolia_search = true
# algolia_appId = ""
# algolia_indexName = ""
# algolia_apiKey = ""

# Sidebar settings
sidebar_about_description = "web系エンジニア歴5年のエンジニアです。バックエンドもフロントエンドも色々やっています。"
sidebar_avatar = "img/profile.jpg" # use absolute URL, seeing it's used in both `/` and `/about/`
featured_tags = true
featured_condition_size = 4
about_me = true
custom_css = ["css/custom.css"]

[params.social]
rss = true
twitter = "https://twitter.com/magic4141"
# linkedin = "https://www.linkedin.com/in/masahiro-hiramori-63b992167/"
# github = "https://github.com/mshr-h"
# googlescholar = "https://scholar.google.com/citations?user=NSCMi88AAAAJ"
# facebook = "https://www.facebook.com/masahiro.hiramori"

# [[params.addtional_menus]]
# title = "CV"
# href = "/top/cv/"

# [[params.addtional_menus]]
# title = "ABOUT"
# href = "/top/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[markup.tableOfContents]
endLevel = 3
startLevel = 2

# [markup.highlight]
# style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
categories = "categories"
tag = "tags"